//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service3.mailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mailService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addEmail", ReplyAction="http://tempuri.org/IService1/addEmailResponse")]
        string addEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendEmailToList", ReplyAction="http://tempuri.org/IService1/sendEmailToListResponse")]
        string sendEmailToList(string subject, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMailingList", ReplyAction="http://tempuri.org/IService1/getMailingListResponse")]
        string[] getMailingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeEmail", ReplyAction="http://tempuri.org/IService1/removeEmailResponse")]
        string removeEmail(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Service3.mailService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Service3.mailService.IService1>, Service3.mailService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addEmail(string email) {
            return base.Channel.addEmail(email);
        }
        
        public string sendEmailToList(string subject, string message) {
            return base.Channel.sendEmailToList(subject, message);
        }
        
        public string[] getMailingList() {
            return base.Channel.getMailingList();
        }
        
        public string removeEmail(string email) {
            return base.Channel.removeEmail(email);
        }
    }
}
